### ISSUE TITLE
Tiebreaking information for the quota method

### ISSUE THREAD

**Issue by DominikPeters** [martinlackner/apportionment#6]
The current implementation of the quota method reports if it encounters a tie at the end of the process:

https://github.com/martinlackner/apportionment/blob/f447b5c9dba402cf0408bd09af2246474398c0e3/apportionment/methods.py#L272-L287

But there can be ties in the middle of the process too, which are broken without message here:
https://github.com/martinlackner/apportionment/blob/f447b5c9dba402cf0408bd09af2246474398c0e3/apportionment/methods.py#L266

It is actually not without loss of generality to focus just on ties that still appear in the end. Here is an example: votes = [720, 720, 120, 120], house size _h_ = 8. Then the quota method selects exactly the following: 3 seats go to each of the big parties, and then choose 1 big party and 1 small party and give those a seat each. This last structure can't be captured by ties just at the end. (In contrast, for divisor methods, the ties are always of the form "assign necessary seats (say there are _t_ of them), and then choose an arbitrary subset of size _h - t_ from a specified set S of parties".)

I don't have a suggestion for a fix. It might well be that the problem "given an instance and a seat assignment, is this seat assignment an outcome of the quota method?" is NP-hard.

**Comment by martinlackner** [comment]
Thanks a lot, Dominik.

* I changed the output of the Quota method so that it always reports if a tie has to be broken, independently of whether this results in more than one possible Quota apportionment.
* Also, tiesallowed=False is no longer allowed for the Quota method, since there is currently no way to check whether more than one Quota apportionment exists. Implementing this would not be hard (at the expense of potentially exponential runtime), but I do not see the necessity of it right now.

If you have a use case that does not work with this solution, let me know. :)
